Repository jenkinsci/templating-engine-plugin, pull requests merged in 2019-07, with the labels that each got.

#5 Arrays in config files
  src/main/groovy/org/boozallen/plugins/jte/config/TemplateConfigDsl.groovy
  src/test/groovy/org/boozallen/plugins/jte/config/TemplateConfigDslSpec.groovy
Labels: bug

#7 fix duplicate config and list ignored changes
  src/main/groovy/org/boozallen/plugins/jte/config/PipelineConfig.groovy
  src/test/groovy/org/boozallen/plugins/jte/config/PipelineConfigSpec.groovy
Labels: bug

#6 fixed false positive change
  src/main/groovy/org/boozallen/plugins/jte/config/PipelineConfig.groovy
  src/test/groovy/org/boozallen/plugins/jte/config/PipelineConfigSpec.groovy
Labels: bug

#8 Docs refactor
  docs/Dockerfile
  docs/_static/style.css
  docs/conf.py
  docs/index.rst
  docs/pages/Governance/config_file_aggregation.rst
  docs/pages/Governance/governance_model.rst
  docs/pages/Governance/governance_tier.rst
  docs/pages/Governance/hierarchical_governance.rst
  docs/pages/Governance/index.rst
  docs/pages/Governance/library_selection.rst
  docs/pages/Governance/pipeline_template_selection.rst
  docs/pages/Library_Development/getting_started.rst
  docs/pages/Library_Development/library_sources.rst
  docs/pages/Library_Development/multimethod_steps.rst
  docs/pages/Library_Development/validate_library_parameters.rst
  docs/pages/Pipeline_Templating/configuration_file_sandboxing.rst
  docs/pages/Pipeline_Templating/configuration_files.rst
  docs/pages/Pipeline_Templating/what_is_a_pipeline_template.rst
  docs/pages/Primitives/application_environments.rst
  docs/pages/Primitives/default_step_implementation.rst
  docs/pages/Primitives/keywords.rst
  docs/pages/Primitives/stages.rst
  docs/pages/Primitives/what_is_a_primitive_in_jte.rst
  docs/pages/Templating/primitives/index.rst
Labels: documentation

#12 Update documentation for pipeline level job config
  .gitignore
  docs/images/Job_Configurations/github_org/governance_tier.png
  docs/images/Job_Configurations/github_org/project_recognizer.png
  docs/images/Job_Configurations/pipeline/flow_definition.png
  docs/images/Job_Configurations/pipeline/pipeline_configuration.png
  docs/images/Job_Configurations/repository/governance_tier.png
  docs/images/Job_Configurations/repository/mode.png
  docs/pages/Job_Configurations/github_org.rst
  docs/pages/Job_Configurations/pipeline.rst
  docs/pages/Job_Configurations/repository.rst
  src/main/groovy/org/boozallen/plugins/jte/TemplateEntryPointVariable.groovy
  src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy
  src/main/resources/org/boozallen/plugins/jte/job/TemplateFlowDefinition/config.jelly
  src/main/resources/org/boozallen/plugins/jte/job/TemplateFlowDefinition/help-sandbox.html
  src/test/groovy/org/boozallen/plugins/jte/config/GovernanceTierSpec.groovy
Labels: skip-changelog

#11 Scm file filenotfound
  src/main/groovy/org/boozallen/plugins/jte/utils/FileSystemWrapper.groovy
  src/test/groovy/org/boozallen/plugins/jte/utils/FileSpec.groovy
Labels: bug
