Repository jenkinsci/templating-engine-plugin, pull requests merged in 2021-01, with the labels that each got.

#147 ignoring docker dependent step tests
  build.gradle
  src/test/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBindingRegistrySpec.groovy
Labels: internal-code-change, skip-changelog

#150 include jte block in 2.0 upgrade docs
  docs/modules/ROOT/pages/upgrade-2.0.adoc
Labels: bug, documentation

#155 Update Issue Templates
  .github/ISSUE_TEMPLATE/1-report-bug.md
  .github/ISSUE_TEMPLATE/2-feature-request.md
  .github/ISSUE_TEMPLATE/3-support.md
Labels: skip-changelog

#159 Fixes Resumability Bug - #158
  build.gradle
  src/main/groovy/org/boozallen/plugins/jte/init/PipelineDecorator.groovy
  src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBinding.groovy
  src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StageInjector.groovy
  src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/Stage.groovy
  src/test/groovy/org/boozallen/plugins/jte/init/ResumabilitySpec.groovy
  src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidatorSpec.groovy
  src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/JteBlockValidatorSpec.groovy
  src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/PipelineConfigVariableSpec.groovy
  src/test/groovy/org/boozallen/plugins/jte/job/AdHocTemplateFlowDefinitionSpec.groovy
  src/test/groovy/org/boozallen/plugins/jte/util/TestUtil.groovy
Labels: bug
